name: Documentation

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: dependencies
      env:
        dependency_packages: doxygen
      run: sudo apt-get update && sudo apt-get -y install ${dependency_packages}

    - name: build
      run: cd doc && doxygen ./Doxyfile

    - name: deploy
      uses: peaceiris/actions-gh-pages@v2.2.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./doc/html
